tasks/update-code.yml
add a mode: deploy code from git
=> add git deploy mode for deploy_via

README.md, defaults/main.yml, tasks/symlink.yml
This PR allows to define an array of shared paths relatives to shared dir that will be symlinked to the release dir.
=> Add support for shared paths

README.md, defaults/main.yml, tasks/update-code/git.yml
The idea is to allow using a private SSH key to do the "GIT pull"
=> Add option to specify SSH key for GIT update

tasks/main.yml
=> Remove redundant/misleading name keys

README.md, defaults/main.yml, tasks/update-code.yml, tasks/update-code/s3.yml
Related to https://github.com/ansistrano/deploy/issues/14
=> Amazon s3 strategy

defaults/main.yml, tasks/update-code.yml, tasks/update-code/git.yml
Fixes #47 (to an acceptable degree at least)
=> Make update-code strategy selection use dynamic include

tasks/symlink-shared.yml, tasks/symlink.yml
=> Ensure symlinks target paths is absent before symlinking #56

README.md, defaults/main.yml, tasks/anon-stats.yml, tasks/main.yml
As you can see, still TBD the url and we still have the problem of our old friend serial + run_once
Things to be done:
=> initial work on an anonymous stats feature

tasks/update-code/copy.yml, tasks/update-code/copy_unarchive.yml
With the addition of the copy_unarchive strategy a tgz file can be deployed using SCP.
=> Ability to deploy archive over scp

tasks/symlink-shared.yml, tasks/symlink.yml
Change absolute by relative_symlinks
=> relative symlinks

README.md, defaults/main.yml, tasks/update-code/copy_unarchive.yml, tasks/update-code/download.yml, tasks/update-code/download_unarchive.yml, tasks/update-code/s3_unarchive.yml
Should cover #100 and should be a replacement for #35 
@kvz can you please have a look at this and tell us what you think?
=> download strategy

README.md
Hi,
I was doing some test with the `ansistrano_deploy_via: "s3"` and took me a while to found that I have to use `_unarchive` suffix.
I just add a few comments to briefly explain it. Is not too much, but I think is enough show that the option exists and how it works.
=> Update inline docs

tasks/rsync-deploy.yml, tasks/symlink-shared.yml, tasks/symlink.yml, test/test.yml
Prevent deletion of shared folders while rsync to current/ and minimize downtime
=> Migration from/to symlink/rsync deployment and .rsync-filter for shared folders (rsync deployment)

tasks/update-code/s3.yml, tasks/update-code/s3_unarchive.yml
=> fix s3 deployment from a folder inside the bucket

README.md
The last link is identical to the first link...
=> De-duplication of talking about us link

tasks/update-code/git.yml
Hi @ricardclau
Maybe shred git_identity_key after used it is a good habit.
So, please review it.
Thanks.
=> Support shred git_identity_key

README.md
We currently don't have a corporate page, thus there is no link. As soon as we have it, I'll submit another PR.
=> Add TechPump company

README.md
Adding yubl.me to the list of companies using Ansistrano.
=> Adding yubl.me

README.md
Adding http://www.fluxus.io/ to the list of sites using ansistrano (sorry for the bombing ... this is the last one :-D )
=> Adding www.fluxus.io

README.md
=> Adding Nodo Ámbar

README.md
Proudly using Ansistrano :)
Thanks!
=> Add Cabissimo to who is using list

README.md
=> Add documentation for rsync requirement

README.md
Added some notes and usage examples to the documentation of the ansistrano_shared_paths and ansistrano_shared_files vars.
=> Improved documentation of ansistrano_shared_paths

README.md, defaults/main.yml, tasks/cleanup.yml, tasks/main.yml, tasks/setup.yml, tasks/update-code.yml, tasks/update-code/rsync.yml
=> clean some variables (BC break)

tasks/update-code/git.yml
Fix deploy of repos with such utf-8 file names as:
- Отличный файл.docx
- Мега-файл.docx
=> Fix non ascii symbols bug.

README.md, tasks/update-code/git.yml
=> Add "refspec" optional argument to the Git deployment method

.travis.yml
I've just added 2.2.2  and 2.3.0
=> Adding newer versions of ansible

README.md
We are using Ansistrano for all the projects that we have and we are really happy with it! :heart:
=> Another website using the Ansistrano Project

README.md
Add simple TOC for quick overview of the docs
=> Add table of content

README.md
Hey guys :beers: 
I'm developing a small cookiecutter project that generates Ansible code that fits the needs of almost every Django project. It is using ansistrano and I `m really happy with it!
I wrote a blog post today for that. Would be happy to place it in the README.md.
Cheers :+1:
=> Add article to the README.md

README.md
Hey,
One of the biggest IT conferences in Bulgaria is deployed via ansistrano. https://hackconf.bg/en/
Thank you guys! That is an awesome project.
Cheers, :beers:
=> Add HackConf to the README.md

tasks/update-code/hg.yml, test/hg.yml, test/main.yml, test/setup.yml
Hey,
I've been evaluating deployment options, ansistrano looks perfect but I'd need mercurial support. I started looking to see if it was simple to add and ended up with this.
It's missing stuff when compared with the git version, but before going any further I wanted to make sure that there's interest merging this, and get any comments you may have on the code so far.
=> Hg support

README.md, defaults/main.yml
Not much else to add to the docs as of now...
=> Update defaults and readme with hg

README.md
More info 👉  https://finizens.com/
☝️ 
@joserobleda @rodrigm @janayama @miguelgf
=> Add Finizens in README

README.md
Hi!
Me and @retrinko developed hosting4devs, a SaaS solution that allows you to manage, in a simple and centralized way, all your servers and PHP apps. We are using Ansistrano to deploy multiple services to servers and Ansible to deploy our infrastructure.
Thanks a lot for this amazing ansible role! 😀
This PR adds hosting4devs to the list of products,companies or teams using Ansistrano.
=> Add hosting4devs as a project using Ansistrano

README.md
Add TMTFactory company which use Ansistrano
=> Add TMTFactory company which use Ansistrano

README.md, tasks/update-code/git.yml
Solves https://github.com/ansistrano/deploy/issues/266
=> add ssh_opts to git strategy

README.md
=> timehook.io using ansistrano

README.md, tasks/update-code/git.yml
Hello :) We need using this parameter for clone very big repository :) You can merge this request?
=> add depth for git module

README.md, tasks/update-code/rsync.yml
I was add 'ansistrano_rsync_use_ssh_args'  optional variable for rsync deployment.
=> Add 'ansistrano_rsync_use_ssh_args' for rsync.

tasks/update-code/git.yml
Using tests as filter will be removed in Ansible 2.9.
=> Using tests as filters is deprecated

tasks/update-code/git.yml
patch for #204 
Thx to @lakiboy for the solution.
=> fixes #204 nested submodules syncing to release path

README.md, tasks/update-code/s3.yml
Fixes https://github.com/ansistrano/deploy/issues/248
=> supporting new ansible 2.3 s3 option

README.md
=> renamed package in README carlosbuenosvinos.ansistrano-deploy  to ansistrano.deploy

README.md
=> Parkimeter uses ansistrano

README.md
Added Cherry Hill to README.md
=> Update README.md - add Cherry Hill

defaults/main.yml, tasks/update-code/unarchive.yml, test/download-test.yml
adding the ability to set the owner and group for the unarchive task
=> Unarchive override group and owner

.yamllint, tasks/rsync-deploy.yml, tasks/symlink.yml, tasks/update-code/git.yml, tasks/update-code/unarchive.yml, test/git-test.yml, test/hg-test.yml, test/rsync-test.yml, test/rsync_direct-test.yml
In order to increase the scoring in Ansible Galaxy.
* https://galaxy.ansible.com/docs/contributing/content_scoring.html
* https://docs.ansible.com/ansible-lint/rules/default_rules.html
=> Fix ansible-lint warnings

README.md
Hi,
Daemonit is very proud to be an ansistrano user :)
Cheers,
Daemonit CEO
=> Daemonit uses Ansistrano

README.md
and i would recommend it any time! ;)
=> two new companies using ansistrano

README.md
Add a link to the talk that I've been giving recently at various user groups and conferences.
=> Add talk link

tasks/update-code/git.yml
make sed for submodule indifferent to system locale (found this issue because someone have it to es_ES)
=> Update git.yml to allow distinct locales

README.md, defaults/main.yml, tasks/rsync-deploy.yml, tasks/symlink-shared.yml
`ansistrano_shared_dir` like `ansistrano_version_dir` or `ansistrano_current_dir`
This will allow the user to change the name of the shared folder.
=> Add ansistrano_shared_dir variable

tasks/update-code.yml, tasks/update-code/git.yml
=> Migrate ansible 11 to ansible 12
