README.md, defaults/main.yml, tasks/update-code.yml, vars/main.yml
@carlosbuenosvinos I moved the variable ```custom_tasks_path``` from the ```vars``` folder to the ```defaults``` just because then the recipe is cleaner as the only way to override a var defined under ```vars``` folder is by defining it again when you specify the role like this:
```yaml
vars:
custom_tasks_path: bar # This gets ignored
roles:
- { role: foo, custom_tasks_path: bar } # This is the only way to override it
```
With this change now it can be defined as a regular variable on the ```vars``` section of the playbook. If you don't agree you can obviously put it back :smile:
=> This PR adds the ability to deploy from a git repo as capistrano used to offer

defaults/main.yml, tasks/update-code.yml
While using rsync through local_action it's perfectly fine, I have found issues using it for slightly more complex deploy setups. For example, when the remote user is not the same as the local user executing the deploy.
Using the **[synchronize](http://docs.ansible.com/synchronize_module.html)** ansible module (a wrapper around rsync) addresses this issue.
Hope you'll find it useful! :)
=> Use of synchronize module

tasks/update-code.yml, tasks/update-code/copy.yml, tasks/update-code/git.yml, tasks/update-code/rsync.yml
In order to organice the deployment strategies and not pollute de update-code.yml, I have created a file per deployment strategy.
=> Group deploy strategies (SCP, GIT and RSYNC for now) into each file

meta/main.yml
The LICENSE file is MIT, not BSD
=> Fix license info in meta

tasks/update-code/git.yml
This is to fix deployments that rely on the git cloning/updating.
1. Removal of the command that's not needed (see #24 )
2. Store the cloned repo in the `repo` dir instead of `shared` that is usually used for other stuff. This follows the capistrano naming practices described here: http://capistranorb.com/documentation/getting-started/structure/
=> Fixes git task: removes unnecessary command and stores repo in repo dir

README.md, meta/main.yml, tasks/update-code.yml
* The ansistrano_release_version can be set from a var to override the computed timestamp
* The timestamp is computed with UTC timezone
* `Z` letter is added as timestamp suffix to prevent TZ confusions when reading the timestamp
See #30
=> Allow to set the release version from var

tasks/update-code/git.yml
The destination path for the ssh keyfile is changed from `~/.ssh/git_identity_key` to `{{ansistrano_deploy_to}}/git_identity_key`
See discussion at #37
=> Copy the git keyfile for git into the deployment path.

tasks/setup.yml
It seems as if the Ansible file module _always_ traverses all files and subdirectories even though it doesn't have any `perms=1234` reason to do so. 
I noticed this on a project when the "Ensure base path" steps were stalling for 20 seconds each.
Since we are not changing perms here, we don't need `recurse=true`.
=> Avoid unnecessary directory recursion

tasks/update-code.yml
Not all environments use g+w. mode should really be set on the server using a umask and not forced in deploy software. This PR is related to issue #39
=> Remove mode="g+w"

tasks/setup.yml, tasks/update-code.yml, tasks/update-code/rsync.yml
Fix for issue #42.
ansistrano_shared_path is only defined in rsync task and it is not the correct value. Now it is registered in setup phase.
Moreover, ansistrano_relases_path registration have been moved to setup phase. In this way is register in its first usage.
=> Fix ansistrano shared path

README.md, defaults/main.yml, tasks/update-code/rsync.yml
I have an ssh alias for one of our servers and ansistrano didn't play nicely with that because it always tried to add [myusername]@alias to the ssh rsync command.
=> Allow ansistrano to work with .ssh config files

tasks/update-code/s3.yml
Adding possibility to use ansible variables for s3 credentials instead of only getting them from ENV.
With this PR you can chose to use ansistrano variables to give the s3 credentials. If they are not given it will work as the current version, getting it from ENV.
=> Adding S3 credentials variables.

README.md, tasks/update-code.yml
Unless overriden by `-e | --extra-vars=`, this generates the release in the same way as before but sets it as a fact once and only once directly, making `ansistrano_timestamp.stdout` redundant(1). The exact assigned value is also conveniently printed in place of the task name.
I believe it adds a certain degree of warming confidence to be able to see the generated ID of the current deploy. You also get a friendly reminder of the variable name, so once you get to the scale where you use `serial`, it will be a bit more clear whether or are successfully overriding it (set_fact becomes skipped).
---
1. Possible BC break: I don't know why this was documented in the README as "two essentially identical variables that you can use"; [when would you _ever_ need the .stdout …
=> Always reveal current release name during deploy

tasks/update-code/rsync.yml
The extra rsync parameters shouldn't be checked by ansible. For example, it
wasn't possible to use multiple `--include` parameters (which is supported by
rsync), because ansible complained about double parameters.
=> quotes variable ansistrano_rsync_extra_params

tasks/update-code/git.yml
When the GitHub deploy key is stored as an encrypted Ansible Vault variable in playbooks it'd be useful to have the [copy key task](/ansistrano/deploy/blob/master/tasks/update-code/git.yml#L3) use the template module instead. In my experience the template module behaves as a superset of copy module so the change would be backwards compatible. 
Imagine playbooks/vars that look like this:
group_vars/all/vault:
```
vault_github_deploy_key: |
-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
```
roles/deploy/templates/deploy_key.pem.j2:
```
{{ vault_github_deploy_key }}
```
and then the updated task in ansistrano:
```
- name: ANSISTRANO | GIT | Ensure GIT deployment key is up to date
template:
src: "{{ ansistrano_git_identity_key_path }}"
dest: "{{ ansistrano_deploy_to …
```
=> use template module for deploy key

tasks/symlink-shared.yml
To get rid of:
`[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the 
full variable syntax ('{{ansistrano_shared_paths}}'). This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`
=> Use the full variable syntax

tasks/update-code/git.yml
Prior to 1.9, the default was `yes` but now it is `no`.
This would avoid errors with succeeding deploys such as:
"Local modifications exist in repository (force=no)"
=> Using "force" when updating repo

tasks/update-code/git.yml
Register the git commit sha into a variable. Currently this variable is not used, but it could be considered to store it in the `REVISION` file or something similar.
Fixes #134
=> Register git commit sha

tasks/symlink-shared.yml
Reduces possible downtime to a minimum by enforcing symlink instead of manually remove it and set it afterwards
We're had some issues with missing shared paths because of the removal and delayed creation.
=> Improve shared path creation in rsync-current mode

defaults/main.yml, tasks/symlink-shared.yml, test/tasks/create-shared-paths.yml, test/test.yml
Hi,
For my workflow, i need to shared both folder and files (symfony app), i show that ansistrano not purpose them, i modify symlink-shared.yml to support shared files.
So now i can set ansistrano_shared_files in the playbook.
```
ansistrano_shared_paths:
- path/of/shared/dir
ansistrano_shared_files:
- path/of/shared/file
```
=> Allow shared files

tasks/symlink-shared.yml, test/tasks/after-symlink.yml
Sorting out regression at #145 
Sorry @mblaschke but even if I hate compromising speed, at the moment maximum compatibility and not introducing regressions is more important to us than gaining some seconds (which in fact is a problem in Ansible) :(
Also, removing force: yes to ensure the symlinks are actually pointing somewhere
=> ensure shared targets are absent is back

README.md, defaults/main.yml, tasks/update-code/git.yml, test/test.yml
Hi @ricardclau 
I added role variable `ansistrano_git_repo_tree` to support repo_tree for git update-code, same as [capistrano repo_path configuration](http://capistranorb.com/documentation/getting-started/configuration/).
Please review it.
Thanks.
=> Support repo_tree for git update-code

tasks/update-code/git.yml
Fixes erratic behaviour of #135. Ansible always registers the variables, even if tasks are skipped. This PR defines two variables, and then defines a third variable, with the previous name, with the value of whichever of the two wasn't skipped.
=> Fix ansistrano_git_result register

README.md, defaults/main.yml, tasks/update-code/s3.yml
I use s3-compatible object storage (Ceph RGW) for storing artifacts.
From ansible v2.2, ansible s3 module supports Ceph RGW.
Now, ansistrano support s3, so I just add an option for supporting Ceph RGW.
* even if use rgw, `ansistrano_deploy_via` is `s3` or `s3_unarchive`
* switch s3 or rgw by `ansistrano_s3_rgw` bool parameter
* when rgw is true, use `ansistrano_s3_url` as an s3 endpoint
* [ansible s3 module](http://docs.ansible.com/ansible/s3_module.html)
* [Ceph RGW](http://docs.ceph.com/docs/jewel/radosgw/)
=> Support s3 rgw option

tasks/setup.yml, tasks/symlink-shared.yml
Related to #113 and #188. It sounds like you're aware of this issue and maybe you don't like this solution, but I figured I'd throw it to the wall and see if it sticks. For me, moving the dir creation to the setup step means that I can follow a pretty sensible deployment order:
1. I specify `ansistrano_shared_files: ["config/database.yml"]`
1. setup task creates `shared/config`
1. My after-setup task populates `shared/config/database.yml` with content, without needing to create the dir
1. symlink-shared task symlinks to this file, which will always exist by now
=> Ensure shared dirs exist during setup

Vagrantfile, example/my-playbook/hosts
This defines the default ssh ports for vagrant to rely on in the host file in the exapmle for testing. Without the definition, you never know the port where vagrant will connect the VM.
=> Define the default ssh ports for testing

meta/main.yml, tasks/anon-stats.yml
This will fix the deprecation warnings. We test against Ansible 1.9, so this should not be a problem.
There is maybe just open question: We define Ansible 1.8 in the meta data, but we test against 1.9. What should be the minimum required version for Ansistrano? I think 1.9 is ok, because its the last of the 1.x branch and 2.x is there quiet a while.
What do you think?
=> Rename sudo to become to avoid deprecation warnings

tasks/update-code/git.yml
Doing so adds support for copying encrypted keys files directly. 
This was added to ansible in 2.1 to the copy command but seemingly not to template.
I tried a workaround with a before-setup script but in order to update git by ssh key a source file is required to be defined. When doing so, it overwrites the valid SSH key that was placed via custom task with the encrypted file.
=> Copy SSH Key with copy rather than template module

README.md, defaults/main.yml, tasks/setup.yml
Hi! I've updated ansistrano from an old version, and the project deployment has failed.
After investigating the problem, I've found a couple of tasks that were added in #142 to prepare shared folders before symlinking. It also makes sense for most of our projects and environments, but in a node from a particular client, the `state: directory` causes the task fails because the path exists as a symlink to another directory in the filesystem.
I think it could be good to make these tasks optional, enabled via ansible defaults, but overridable by the user. For now that approach is working for us.
=> Makes optional shared paths and basedir shared files creation

README.md
Hi!
In Doalitic we developed [Moss](https://moss.sh), a Sysadmin-as-a-Service, and we are using Ansistrano to deploy sites to servers.
We are very happy with the impressive work you've done, thanks! 😀 
This PR adds Moss to the list of products/companies using Ansistrano.
=> Add Moss as a product using Ansistrano

defaults/main.yml, tasks/update-code/rsync.yml
In Ansible 2.3, the way the rsync command line is built changed (see
ansible/ansible#23575), which caused the default empty string not to be
stripped, but included in the command. This in turn caused rsync to
always include the current working directory as source (As this is what
an empty argument apparently resolves to).
This workaround removes the default setting and adds a filter that omits
the parameter if it's not defined.
Fixes #227 and related.
=> workaround rsync quoting bug

tasks/rsync-deploy.yml, tasks/symlink-shared.yml
This fixes the broken shared file symlinks of rsynced deployment. Current build creates shared file symlinks pointing to files in ../../shared on rsynced deployment but it should point to ../shared instead.
=> Correct symlinks via rsync

tasks/setup.yml
ansistrano_shared_path is create but note use on all playbook role.
Add this variable on the setup task for create shared basedir
=> use ansistrano_shared_path varaible on setup task

README.md
We use it too, thanks for the excellent work. We've been using Capistrano for a time and Ansible for server setups but now we are using Ansistrano for Symfony 4 deployments. MEDIA.figaro ([media.figaro.fr](http://media.figaro.fr)) is the advertisement department of one of the main french newspaper Le Figaro (www.lefigaro.fr). Best, Kendrick (www.kendrick.it).
=> MEDIA.figaro user

defaults/main.yml, tasks/update-code/git.yml, tasks/update-code/hg.yml, tasks/update-code/svn.yml, test/setup.yml
I have a site where the code is split into 2 repositories. When setting up Ansistrano to deploy in this scenario, I noticed that, when I deploy one repo, the directory "repo" gets clobbered when I deploy the second repo. Being able to name that directory resolves the name collision.
=> Adding feature to give a custom name to the checked out site repository.

tasks/symlink-shared.yml
Python 3.7 subtly changed the behavior of re.sub() which leads to paths
like `..../....` where they should look like `../..`.
By matching only non-empty path segments, there is no second adjacent
empty match that would be replaced.
Fixes #302
=> Fix regular expression mistake in Python 3.7

.gitattributes
Based on the trick from https://github.com/ansible/galaxy/issues/78,
I propose a `.gitattributes` file for excluding tests-related files from Ansible Galaxy.
It's not much but I had an issue with the symlink `test/roles/local-ansistrano`, I got caught in a loop with `rsync --copy-dirlinks` because of this relative symlink.
=> Exclude tests files from Ansible Galaxy

tasks/setup.yml
This includes the fix from #328, and fixes a few more. Example deprecation warnings we're seeing:
```
[DEPRECATION WARNING]: evaluating ansistrano_ensure_shared_paths_exist as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also
see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
```
[DEPRECATION WARNING]: evaluating ansistrano_ensure_basedirs_shared_files_exist as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the
future. Also see CONDITIONAL_BARE_VARS configuration toggle.. This feature will be removed in version 2.12. Deprecation warnings …
```
=> Fix Ansible 2.8 bare variable deprecation warnings

tasks/cleanup.yml
I faced the following problem when I made a Python upgrade to 3.7.4:
```
fatal: [host]: FAILED! => {}
MSG:
The conditional check 'ansistrano_keep_releases > 0' failed. The error was: Unexpected templating type error occurred on ({% if ansistrano_keep_releases > 0 %} True {% else %} False {% endif %}): '>' not supported between instances of 'str' and 'int'
The error appears to have been in '/path/to/playbook/roles/ansistrano.deploy/tasks/cleanup.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: ANSISTRANO | Clean up releases
^ here
```
The problem was in `when` statement:
`when: ansistrano_keep_releases > 0`
`ansistrano_keep_releases` is treated as a string, but there we have comparison int and string. …
=> Add ansistrano_keep_releases casting to int to avoid "Unexpected templating type error"

README.md, tasks/update-code/rsync_direct.yml, test/main.yml, test/rsync_direct-test.yml
Adds a `rsync_direct` deployment strategy which is slightly faster than the default `rsync` because it skips the copy step from the `ansistrano_shared_rsync_copy_path` to `ansistrano_release_path` for #243
=> Add rsync_direct deployment strategy

test/setup.yml
From logs:
> [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
> squash_actions is deprecated. Instead of using a loop to supply multiple items 
> and specifying `name: "{{ item }}"`, please use `name: ['rsync', 'tar', 'ssh', 
> 'git', 'unzip', 'subversion', 'mercurial']` and remove the loop. This feature 
> will be removed in version 2.11. Deprecation warnings can be disabled by 
> setting deprecation_warnings=False in ansible.cfg.
=> Avoid Apt deprecation warning

test/setup.yml
From logs:
> [DEPRECATION WARNING]: Invoking "yum" only once while using a loop via 
> squash_actions is deprecated. Instead of using a loop to supply multiple items 
> and specifying `name: "{{ item }}"`, please use `name: ['rsync', 'tar', 
> 'openssh-clients', 'git', 'unzip', 'subversion', 'mercurial', 'findutils']` and
>  remove the loop. This feature will be removed in version 2.11. Deprecation 
> warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
=> Avoid Yum deprecation warning

README.md, defaults/main.yml, tasks/update-code/git.yml
My deployment failed on a managed server, where git was not installed in the usual binary path. 
So I added the possibility to change the executable path for git.
=> Added the option to change the executable path for git

README.md, tasks/update-code/s3.yml
Some cloud providers like OpenStack Swift from [OVH]( https://www.ovhcloud.com/en-gb/public-cloud/object-storage/) in EC2 mode need this region parameter to work.
Here is an example of how we're using this small change in our stack :
```yaml
ansistrano_deploy_via: s3_unarchive
ansistrano_s3_bucket: "some-bucket"
ansistrano_s3_object: "some-object.tar.gz"
ansistrano_s3_rgw: true
ansistrano_s3_aws_access_key: "{{ vaulted_access_key }}"
ansistrano_s3_aws_secret_key: "{{ vaulted_secret_key }}"
ansistrano_s3_url: "https://s3.gra.cloud.ovh.net"
ansistrano_s3_region: gra
```
=> Add region in "Get object from Ceph RGW" task

tasks/funding.yml
Hi. When the funding.yml tasks are executed on a large inventory, they are literally spamming the console output with the funding info for every host. It makes scrolling up to see the deployment console output somewhat difficult; It can even hide the beginning of the output on some terminals limiting the number of lines you can scroll up in history.
This PR adds `run_once: true` to the funding.yml tasks, so that sponsors are only displayed once (and not 2 times 200 if I have an inventory of 200 hosts).
=> Add run_once on funding tasks

tasks/update-code/git.yml
fixes ansistrano/deploy#391
Tested with the following values of ansistrano_git_repo_tree
Tested setting ansistrano_git_repo_tree to the following:
unset
""
"/"
"/foo"
"/foo/"
"foo/"
"foo//"
=> Set ansistrano_git_real_repo_tree to match only 1 directory
